[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
blackbox_program = "4LCZpohjxXFNfT2KtTdPsqXNVbUxW2RwaW91CMv3geaQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
